
library(BayesFactor)
library(fabricatr)
library(readr)
library(tidyverse)
library(here)
library(brms)
library(purrr)
library(ggplot2)
library(forcats)
library(ggjoy)
library(knitr)
library(tidyverse)
library(coda)
library(mvtnorm)
# devtools::install_github("rmcelreath/rethinking")
library(rethinking)
library(brms)
library(dplyr)
